const START_FETCHING = "START_FETCHING";
const FETCHING_COMPLETED = "FETCHING_COMPLETED";
const SET_ERROR = "SET_ERROR";
const HIDE_ERROR = "HIDE_ERROR";
const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
const SET_SUCCESS = "SET_SUCCESS";

export {
  START_FETCHING,
  FETCHING_COMPLETED,
  SET_ERROR,
  HIDE_ERROR,
  CLOSE_SNACKBAR,
  SET_SUCCESS,
};
