const SET_SELECTED_ENCOUNTER = "SET_SELECTED_ENCOUNTER";
const RESET_SELECTED_ENCOUNTER = "RESET_SELECTED_ENCOUNTER";
const SET_EDITOR_TEXT = "SET_EDITOR_TEXT";
const RESET_EDITOR_TEXT = "RESET_EDITOR_TEXT";
const SAVE_LAYOUT = "SAVE_LAYOUT";

const SET_PATIENT_ID = "SET_PATIENT_ID";

const SET_PATIENT_INFO = "SET_PATIENT_INFO";
const SET_PATIENT_HISTORY = "SET_PATIENT_HISTORY";
const TOGGLE_PATIENT_DIALOG_TYPE = "TOGGLE_PATIENT_DIALOG_TYPE";
const TOGGLE_PATIENT_APPOINTMENT_HISORY_DIALOG = "TOGGLE_PATIENT_APPOINTMENT_HISORY_DIALOG";
const TOGGLE_PATIENT_INFO_EDIT_DIALOG = "TOGGLE_PATIENT_INFO_EDIT_DIALOG";
const TOGGLE_PATIENT_INFO_HISORY_DIALOG = "TOGGLE_PATIENT_INFO_HISORY_DIALOG";

const SET_ADMIN_NOTES = "SET_ADMIN_NOTES";
const TOGGLE_ADMIN_NOTES_EDIT_FORM = "TOGGLE_ADMIN_NOTES_EDIT_FORM";
const TOGGLE_ADMIN_NOTES_HISTORY_DIALOG = "TOGGLE_ADMIN_NOTES_HISTORY_DIALOG";

const SET_FORMS = "SET_FORMS";
const TOGGLE_FORM_EXPAND_DIALOG = "TOGGLE_FORM_EXPAND_DIALOG";
const TOGGLE_FORM_VIEW_DIALOG = "TOGGLE_FORM_VIEW_DIALOG";

const SET_BILLING = "SET_BILLING";
const SET_SELECTED_BILLING = "SET_SELECTED_BILLING";
const RESET_SELECTED_BILLING = "RESET_SELECTED_BILLING";
const SET_BALANCE = "SET_BALANCE";

const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";

const TOGGLE_BILLING_NEW_TRANSACTION_DIALOG = "TOGGLE_BILLING_NEW_TRANSACTION_DIALOG";
const TOGGLE_BILLING_NEW_DIALOG = "TOGGLE_BILLING_NEW_DIALOG";
const TOGGLE_BILLING_EXPAND_DIALOG = "TOGGLE_BILLING_EXPAND_DIALOG";

const SET_ALLERGIES = "SET_ALLERGIES";
const TOGGLE_ALLERGIES_NEW_DIALOG = "TOGGLE_ALLERGIES_NEW_DIALOG";
const TOGGLE_ALLERGIES_EXPAND_DIALOG = "TOGGLE_ALLERGIES_EXPAND_DIALOG";

const SET_HANDOUTS = "SET_HANDOUTS";
const TOGGLE_HANDOUTS_NEW_DIALOG = "TOGGLE_HANDOUTS_NEW_DIALOG";
const TOGGLE_HANDOUTS_EXPAND_DIALOG = "TOGGLE_HANDOUTS_EXPAND_DIALOG";

const SET_ENCOUNTERS = "SET_ENCOUNTERS";
const TOGGLE_ENCOUNTERS_NEW_DIALOG = "TOGGLE_ENCOUNTERS_NEW_DIALOG";
const TOGGLE_ENCOUNTERS_EXPAND_DIALOG = "TOGGLE_ENCOUNTERS_EXPAND_DIALOG";

const SET_MEDICAL_NOTES = "SET_MEDICAL_NOTES";
const TOGGLE_MEDICAL_NOTES_HISTORY_DIALOG = "TOGGLE_MEDICAL_NOTES_HISTORY_DIALOG";
const TOGGLE_MEDICAL_NOTES_EDIT_FORM = "TOGGLE_MEDICAL_NOTES_EDIT_FORM";

const SET_MESSAGES = "SET_MESSAGES";
const SET_SELECTED_MESSAGE = "SET_SELECTED_MESSAGE";
const RESET_SELECTED_MESSAGE = "RESET_SELECTED_MESSAGE";
const SET_MESSAGE_TYPE = "SET_MESSAGE_TYPE";
const TOGGLE_MESSAGES_NEW_DIALOG = "TOGGLE_MESSAGES_NEW_DIALOG";
const TOGGLE_MESSAGES_EXPAND_DIALOG = "TOGGLE_MESSAGES_EXPAND_DIALOG";
const TOGGLE_MESSAGES_DIALOG_PAGE = "TOGGLE_MESSAGES_DIALOG_PAGE";

const SET_MEDICATIONS = "SET_MEDICATIONS";
const SET_SELECTED_MEDICATION = "SET_SELECTED_MEDICATION";
const RESET_SELECTED_MEDICATION = "RESET_SELECTED_MEDICATION";
const TOGGLE_MEDICATION_NEW_DIALOG = "TOGGLE_MEDICATION_NEW_DIALOG";
const TOGGLE_MEDICATION_EXPAND_DIALOG = "TOGGLE_MEDICATION_EXPAND_DIALOG";

const SET_DIAGNOSES = "SET_DIAGNOSES";
const SET_ACTIVE_DIAGNOSES = "SET_ACTIVE_DIAGNOSES";
const TOGGLE_DIAGNOSES_NEW_DIALOG = "TOGGLE_DIAGNOSES_NEW_DIALOG";
const TOGGLE_DIAGNOSES_EXPAND_DIALOG = "TOGGLE_DIAGNOSES_EXPAND_DIALOG";
const SET_DIAGNOSES_STATUS = "SET_DIAGNOSES_STATUS";

const SET_REQUISITIONS = "SET_REQUISITIONS";
const TOGGLE_REQUISITIONS_NEW_DIALOG = "TOGGLE_REQUISITIONS_NEW_DIALOG";
const TOGGLE_REQUISITIONS_EXPAND_DIALOG = "TOGGLE_REQUISITIONS_EXPAND_DIALOG";

const SET_DOCUMENTS = "SET_DOCUMENTS";
const TOGGLE_DOCUMENTS_EXPAND_DIALOG = "TOGGLE_DOCUMENTS_EXPAND_DIALOG";

const TOGGLE_INSIGHTS_EXPAND_DIALOG = "TOGGLE_INSIGHTS_EXPAND_DIALOG";

const SET_TESTS = "SET_TESTS";
const TOGGLE_TESTS_EXPAND_DIALOG = "TOGGLE_TESTS_EXPAND_DIALOG";
const TOGGLE_TESTS_CHART_EXPAND_DIALOG = "TOGGLE_TESTS_CHART_EXPAND_DIALOG";
const SET_TEST_NAME = "SET_TEST_NAME";
const SET_SELECTED_TEST = "SET_SELECTED_TEST";

const RESET_STORE = "RESET_STORE";

export {
  SET_SELECTED_ENCOUNTER,
  RESET_SELECTED_ENCOUNTER,
  SET_EDITOR_TEXT,
  RESET_EDITOR_TEXT,
  SAVE_LAYOUT,
  // Setters
  SET_PATIENT_ID,
  SET_PATIENT_INFO,
  SET_PATIENT_HISTORY,
  TOGGLE_PATIENT_DIALOG_TYPE,
  TOGGLE_PATIENT_APPOINTMENT_HISORY_DIALOG,
  SET_ADMIN_NOTES,
  SET_FORMS,
  SET_BILLING,
  SET_SELECTED_BILLING,
  RESET_SELECTED_BILLING,
  SET_BALANCE,
  SET_ALLERGIES,
  SET_HANDOUTS,
  SET_ENCOUNTERS,
  SET_MEDICAL_NOTES,
  SET_SELECTED_MESSAGE,
  RESET_SELECTED_MESSAGE,
  SET_MESSAGE_TYPE,
  SET_MESSAGES,
  SET_MEDICATIONS,
  SET_SELECTED_MEDICATION,
  RESET_SELECTED_MEDICATION,
  SET_DIAGNOSES,
  SET_ACTIVE_DIAGNOSES,
  SET_DIAGNOSES_STATUS,
  SET_REQUISITIONS,
  SET_DOCUMENTS,
  SET_TESTS,
  SET_PAYMENT_METHODS,
  // Togglers
  TOGGLE_PATIENT_INFO_EDIT_DIALOG,
  TOGGLE_PATIENT_INFO_HISORY_DIALOG,
  TOGGLE_ADMIN_NOTES_EDIT_FORM,
  TOGGLE_ADMIN_NOTES_HISTORY_DIALOG,
  TOGGLE_FORM_EXPAND_DIALOG,
  TOGGLE_FORM_VIEW_DIALOG,
  TOGGLE_BILLING_NEW_TRANSACTION_DIALOG,
  TOGGLE_BILLING_NEW_DIALOG,
  TOGGLE_BILLING_EXPAND_DIALOG,
  TOGGLE_ALLERGIES_NEW_DIALOG,
  TOGGLE_ALLERGIES_EXPAND_DIALOG,
  TOGGLE_HANDOUTS_NEW_DIALOG,
  TOGGLE_HANDOUTS_EXPAND_DIALOG,
  TOGGLE_ENCOUNTERS_NEW_DIALOG,
  TOGGLE_ENCOUNTERS_EXPAND_DIALOG,
  TOGGLE_MEDICAL_NOTES_HISTORY_DIALOG,
  TOGGLE_MEDICAL_NOTES_EDIT_FORM,
  TOGGLE_MESSAGES_NEW_DIALOG,
  TOGGLE_MESSAGES_EXPAND_DIALOG,
  TOGGLE_MESSAGES_DIALOG_PAGE,
  TOGGLE_MEDICATION_NEW_DIALOG,
  TOGGLE_MEDICATION_EXPAND_DIALOG,
  TOGGLE_DIAGNOSES_NEW_DIALOG,
  TOGGLE_DIAGNOSES_EXPAND_DIALOG,
  TOGGLE_REQUISITIONS_NEW_DIALOG,
  TOGGLE_REQUISITIONS_EXPAND_DIALOG,
  TOGGLE_DOCUMENTS_EXPAND_DIALOG,
  TOGGLE_INSIGHTS_EXPAND_DIALOG,
  TOGGLE_TESTS_EXPAND_DIALOG,
  TOGGLE_TESTS_CHART_EXPAND_DIALOG,
  SET_TEST_NAME,
  SET_SELECTED_TEST,
  RESET_STORE,
};
