const SET_SELECTED_ENCOUNTER = "SET_SELECTED_ENCOUNTER";
const RESET_SELECTED_ENCOUNTER = "RESET_SELECTED_ENCOUNTER";
const SET_EDITOR_TEXT = "SET_EDITOR_TEXT";
const RESET_EDITOR_TEXT = "RESET_EDITOR_TEXT";

export {
  SET_SELECTED_ENCOUNTER,
  RESET_SELECTED_ENCOUNTER,
  SET_EDITOR_TEXT,
  RESET_EDITOR_TEXT,
};
